### ISSUE TITLE
preg_replace has stricter rules in PHP7.3

### ISSUE THREAD

**Issue by NiklasAurora** [canax/textfilter#1]
```
PHP version: PHP 7.3.9 (cli) (built: Aug 30 2019 01:42:25) ( NTS )
Composer version: Composer version 1.9.0 2019-08-02 20:55:32
```

The following row uses preg_replace, which now has a stricter ruleset in PHP versions above 7.3.

https://github.com/canax/textfilter/blob/a90177cd404b093541222fd0d6cf71907ac2ce25/src/TextFilter/TTextUtilities.php#L143-L147

Which results in the following error message:

```
Warning: preg_replace(): Compilation failed: invalid range in character class at offset 17 in /Users/nik/htdocs/dbwebb.se/vendor/mos/ctextfilter/src/TextFilter/TTextUtilities.php on line 144
```

It could be related to this thread:

https://stackoverflow.com/questions/24764212/preg-match-compilation-failed-invalid-range-in-character-class-at-offset

**Comment by mosbth** [comment]
Fixed in https://github.com/canax/textfilter/commit/a90177cd404b093541222fd0d6cf71907ac2ce25

A backslash before `-`.
https://github.com/canax/textfilter/blob/a90177cd404b093541222fd0d6cf71907ac2ce25/src/TextFilter/TTextUtilities.php#L141
